# User config
author: "Penumbra (魑魅魍魉)"
tagline: "Experimental music and film in Shanghai"
description: "Event series for experimental music and film, hosted at Elevator in Shanghai."
keywords: "Shanghai, Film, Events"
email: "penumbra.events@gmail.com"
instagram: "https://instagram.com/penumbra.events"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed