# User config
author: "Penumbra &#8226; 魑魅魍魉"
tagline: "Experimental music and film in Shanghai"
description: "Experimental music and film at Elevator, Shanghai."
keywords: "Shanghai, Film, Events"
email: "penumbra.events@gmail.com"
instagram: "https://instagram.com/penumbra.events"

# if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
domain: etc.github.io

# the base hostname and protocol for your site
url: https://etc.github.io  

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed